version: '3.1'

services:
  web:
    build: .
    container_name: servidor_pdf
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    container_name: base_datos_pdf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_reportes
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
    ports:
      - "3310:3306"
